name: 'Terraform'

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUB_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TFSTATE_RG: tfstate
      STORAGEACCOUNTNAME: akstfstate001
      CONTAINERNAME: akscs
      TF_VAR_subscription_id: ${{ secrets.AZURE_SUB_ID }}
      TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}

    runs-on: ubuntu-latest
  #  environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Conenct into your Azure subscription
    - name: Connect to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.DEPLOYMENT_SP }}

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.DEPLOYMENT_SP }}

    # Initialize the TF working directory.
    # Change the backend-config variables to match the storage account used for your deployments.
    - name: Terraform Init 03-AAD
      working-directory: ./Scenarios/AKS-Secure-Baseline-PrivateCluster/Terraform/03-AAD-import
      run: terraform init -input=false -backend-config="resource_group_name=$TFSTATE_RG" -backend-config="storage_account_name=$STORAGEACCOUNTNAME" -backend-config="container_name=$CONTAINERNAME"

    # Generates an execution plan for Terraform
    - name: Terraform Plan 03-AAD
      working-directory: ./Scenarios/AKS-Secure-Baseline-PrivateCluster/Terraform/03-AAD-import
      run: terraform plan -input=false

      # On push to main, build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply 03-AAD
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      working-directory: ./Scenarios/AKS-Secure-Baseline-PrivateCluster/Terraform/03-AAD-import
      run: terraform apply -input=false -auto-approve